<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="chetan-PC" ignored="0" name="Default test" tests="6" failures="1" timestamp="28 Dec 2018 11:38:08 GMT" time="80.117" errors="0">
  <testcase name="verifySalesTypeName" time="0.01" classname="com.test.testcases.SalesTypesPageTest"/>
  <testcase name="verifySalesTypesTittle" time="0.022" classname="com.test.testcases.SalesTypesPageTest">
    <failure type="java.lang.AssertionError" message="expected [Sals Types] but found [Sales Types]">
      <![CDATA[java.lang.AssertionError: expected [Sals Types] but found [Sales Types]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.test.testcases.SalesTypesPageTest.verifySalesTypesTittle(SalesTypesPageTest.java:51)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verifySalesTypesTittle -->
  <testcase name="LoginPageDataTest" time="0.44" classname="com.test.testcases.SalesTypesPageTest"/>
  <testcase name="LoginPageDataTest" time="0.603" classname="com.test.testcases.SalesTypesPageTest"/>
  <testcase name="LoginPageDataTest" time="0.424" classname="com.test.testcases.SalesTypesPageTest"/>
  <testcase name="LoginPageDataTest" time="0.453" classname="com.test.testcases.SalesTypesPageTest"/>
</testsuite> <!-- Default test -->
